name: preview-automerge

on:
  pull_request:
    types: [labeled, synchronize]

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'preview-target')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find and merge all preview PRs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RESPONSE=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/pulls?state=open&labels=preview")

          PR_COUNT=$(echo "$RESPONSE" | jq '. | length')

          if [ "$PR_COUNT" -eq "0" ]; then
            echo "No PRs with preview label found"
            exit 0
          fi

          echo "Found $PR_COUNT PRs with preview label"

          for i in $(seq 0 $(("$PR_COUNT" - 1))); do
            PR_NUMBER=$(echo "$RESPONSE" | jq -r ".[$i].number")
            PR_TITLE=$(echo "$RESPONSE" | jq -r ".[$i].title")

            echo "Processing PR #$PR_NUMBER: $PR_TITLE"

            MERGE_RESULT=$(curl -s -X PUT \
              -H "Authorization: token $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/merge" \
              -d '{"merge_method":"merge"}')

            if echo "$MERGE_RESULT" | jq -e '.merged == true' > /dev/null; then
              echo "✅ Successfully merged PR #$PR_NUMBER"
            else
              ERROR_MSG=$(echo "$MERGE_RESULT" | jq -r '.message')
              echo "❌ Failed to merge PR #$PR_NUMBER: $ERROR_MSG"
            fi
          done
