name: auto-merge

on:
  pull_request:
    types: [labeled, synchronize]

permissions:
  contents: write
  pull-requests: write

jobs:
  merge-to-preview:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'preview-target')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Find preview PRs and merge content
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 現在のPR（preview-target）のブランチ情報を取得
          TARGET_BRANCH="${{ github.event.pull_request.head.ref }}"
          TARGET_SHA="${{ github.event.pull_request.head.sha }}"
          echo "Current PR branch: $TARGET_BRANCH (SHA: $TARGET_SHA)"

          # GitHub REST APIを使用して「preview」ラベルがついたすべてのPRを検索
          RESPONSE=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/pulls?state=open&labels=preview")

          # 検索結果からPR数を取得
          PR_COUNT=$(echo $RESPONSE | jq '. | length')

          if [ "$PR_COUNT" -eq "0" ]; then
            echo "No PRs with preview label found"
            exit 0
          fi

          echo "Found $PR_COUNT PRs with preview label"

          # すべてのプレビューPRに対して処理
          for i in $(seq 0 $(($PR_COUNT - 1))); do
            PR_NUMBER=$(echo $RESPONSE | jq -r ".[$i].number")
            PREVIEW_BRANCH=$(echo $RESPONSE | jq -r ".[$i].head.ref")
            
            echo "Processing preview PR #$PR_NUMBER (branch: $PREVIEW_BRANCH)"
            
            # プレビューブランチをチェックアウト
            git fetch origin $PREVIEW_BRANCH
            git checkout $PREVIEW_BRANCH
            
            # preview-targetブランチの内容をマージ（直接コミットとして適用）
            echo "Applying changes from $TARGET_BRANCH to $PREVIEW_BRANCH"
            if git merge --no-ff origin/$TARGET_BRANCH -m "Apply preview-target changes from $TARGET_BRANCH"; then
              # 変更をプッシュ
              git push origin $PREVIEW_BRANCH
              echo "✅ Successfully applied changes to preview branch $PREVIEW_BRANCH"
              
              # PRにコメントを追加
              curl -s -X POST \
                -H "Authorization: token $GITHUB_TOKEN" \
                -H "Accept: application/vnd.github.v3+json" \
                "https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER/comments" \
                -d "{\"body\":\"✅ Preview updated with changes from branch \`$TARGET_BRANCH\` (SHA: $TARGET_SHA)\"}"
            else
              echo "❌ Failed to apply changes due to conflicts"
              git merge --abort
              
              # PRにコメントを追加
              curl -s -X POST \
                -H "Authorization: token $GITHUB_TOKEN" \
                -H "Accept: application/vnd.github.v3+json" \
                "https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER/comments" \
                -d "{\"body\":\"❌ Failed to update preview with changes from \`$TARGET_BRANCH\` due to merge conflicts. Manual intervention required.\"}"
            fi
          done
